const operation = document.querySelector('[data-operation]')
const result = document.querySelector('[data-result]')
const clear = document.querySelector('[data-clear]')
const operator = document.querySelectorAll('[data-operator]')
const number = document.querySelectorAll('[data-number]')
const number = document.querySelector('[data-equals]')
